pipeline {
    agent any 
    stages {
	stage('Build'){
	    steps {
	    	echo 'Starting up eureka cluster...'
		withKubeConfig(caCertificate: '', credentialsId: 'ff218051-42b7-459c-b199-2c82c7063ee4', serverUrl: 'platform-test-eureka-ca213c38.hcp.eastus.azmk8s.io') {
    		    sh 'kubectl get nodes'
		}


	    }
	}

       # stage('DNS Assignment') {
        #    steps {
         #       echo 'Testing Java App...'
          #      sh './update-public-ip-dns.sh eureka1 eurekatest-vincent eureka1svc'
           #     echo 'Assignment complete'
            #}
        #}
    }
}
