apiVersion: v1
kind: Service
metadata:
  name: eureka1-headless
  namespace: eurekatest-vincent #cse-platform-viji
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: eureka1

